// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4_1Contacts.Models;

#nullable disable

namespace _4_1Contacts.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_4_1Contacts.Models.Categories", b =>
                {
                    b.Property<string>("CategoriesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoriesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriesId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoriesId = "Fr",
                            CategoriesName = "Friend"
                        },
                        new
                        {
                            CategoriesId = "Fa",
                            CategoriesName = "Family"
                        },
                        new
                        {
                            CategoriesId = "W",
                            CategoriesName = "Work"
                        },
                        new
                        {
                            CategoriesId = "S",
                            CategoriesName = "School"
                        },
                        new
                        {
                            CategoriesId = "C",
                            CategoriesName = "Church"
                        });
                });

            modelBuilder.Entity("_4_1Contacts.Models.Contacts", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("CategoriesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            CategoriesId = "S",
                            DateAdded = new DateTime(2024, 2, 25, 1, 45, 13, 390, DateTimeKind.Utc).AddTicks(2776),
                            Email = "10934984@uvu.edu",
                            FirstName = "Peter",
                            LastName = "Sanford",
                            Organization = "UVU",
                            Phone = "801-953-3509"
                        },
                        new
                        {
                            ContactId = 2,
                            CategoriesId = "Fr",
                            DateAdded = new DateTime(2024, 2, 25, 1, 45, 13, 390, DateTimeKind.Utc).AddTicks(2778),
                            Email = "billy.bob@madeup.com",
                            FirstName = "Billy",
                            LastName = "Bob",
                            Organization = "Billy's Boats",
                            Phone = "801-953-3508"
                        });
                });

            modelBuilder.Entity("_4_1Contacts.Models.Contacts", b =>
                {
                    b.HasOne("_4_1Contacts.Models.Categories", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
